package com.bdqn.module;
import com.zxs.utils.lang.EmptyUtils;
import com.zxs.utils.lang.StringUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BdqnArticle implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.source
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.created_date
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.updated_date
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.status
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.content
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private String content;

    /**
     * html 源码
     */
    private String contentHtml;
    /**
     * 点赞的次数
     */
    private int likes;
    /**
     * 来源网站
     */
    private String sourceWap;
    /**
     * 责任编辑
     */
    private String sourceEditor;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.id
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bdqn_article.title
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private String title;
    /**
     *
     */
    private String type;

    public int getLikes() {
        return likes;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bdqn_article
     *
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    private static final long serialVersionUID = 1L;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bdqn_article.source
     *
     * @return the value of bdqn_article.source
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bdqn_article.source
     *
     * @param source the value for bdqn_article.source
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bdqn_article.created_date
     *
     * @return the value of bdqn_article.created_date
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bdqn_article.created_date
     *
     * @param createdDate the value for bdqn_article.created_date
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bdqn_article.updated_date
     *
     * @return the value of bdqn_article.updated_date
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bdqn_article.updated_date
     *
     * @param updatedDate the value for bdqn_article.updated_date
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bdqn_article.status
     *
     * @return the value of bdqn_article.status
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bdqn_article.status
     *
     * @param status the value for bdqn_article.status
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bdqn_article.content
     *
     * @return the value of bdqn_article.content
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bdqn_article.content
     *
     * @param content the value for bdqn_article.content
     * @mbggenerated Thu Jan 07 15:37:17 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getContentHtml() {
        return contentHtml;
    }

    public void setContentHtml(String contentHtml) {
        this.contentHtml = contentHtml;
    }

    public String getSourceWap() {
        return sourceWap;
    }

    public void setSourceWap(String sourceWap) {
        this.sourceWap = sourceWap;
    }

    public String getSourceEditor() {
        return sourceEditor;
    }

    public void setSourceEditor(String sourceEditor) {
        this.sourceEditor = sourceEditor;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}